"""
TestSphere-AI — Shared Enumerations

Defines all enums used across the AI intelligence layer and
inter-member communication contracts.
"""

from enum import Enum


class FailureType(str, Enum):
    """Classification categories for test failures.

    Used by the Failure Analysis Agent to categorize why a test failed,
    which determines whether self-healing is applicable.
    """

    ELEMENT_NOT_FOUND = "ELEMENT_NOT_FOUND"
    ELEMENT_NOT_INTERACTABLE = "ELEMENT_NOT_INTERACTABLE"
    TIMEOUT = "TIMEOUT"
    ASSERTION_FAILURE = "ASSERTION_FAILURE"
    NAVIGATION_FAILURE = "NAVIGATION_FAILURE"
    NETWORK_ERROR = "NETWORK_ERROR"
    APPLICATION_ERROR = "APPLICATION_ERROR"
    UNKNOWN = "UNKNOWN"


class HealingStatus(str, Enum):
    """Status of a healing attempt.

    Tracks the lifecycle of a self-healing operation from proposal
    through validation by Member 2's execution engine.
    """

    PROPOSED = "PROPOSED"
    VALIDATION_PENDING = "VALIDATION_PENDING"
    VALIDATED_SUCCESS = "VALIDATED_SUCCESS"
    VALIDATED_FAILURE = "VALIDATED_FAILURE"
    NO_SAFE_HEALING_FOUND = "NO_SAFE_HEALING_FOUND"


class TestPriority(str, Enum):
    """Priority levels for generated test cases.

    Definitions
    -----------
    CRITICAL:
        System-critical functionality whose failure blocks all usage.
    HIGH:
        Critical user workflows or high-impact functionality.
        Examples: Login, Signup, Payment, Checkout, critical form submission.
    MEDIUM:
        Important functionality that is not immediately business-critical.
    LOW:
        Minor or low-impact functionality.
    """

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class TestCategory(str, Enum):
    """Categories of test cases generated by the Test Planner.

    Definitions
    -----------
    FUNCTIONAL:
        Tests expected normal user workflows.
    NEGATIVE:
        Tests invalid or incorrect input/workflows.
    BOUNDARY:
        Tests minimum, maximum, empty, or edge-case values.
    SMOKE:
        Quick sanity checks that core features work.
    REGRESSION:
        Tests that verify previously working functionality still works.
    EDGE_CASE:
        Tests for unusual or extreme conditions.
    ACCESSIBILITY:
        Tests that verify accessibility compliance.
    """

    FUNCTIONAL = "functional"
    NEGATIVE = "negative"
    BOUNDARY = "boundary"
    SMOKE = "smoke"
    REGRESSION = "regression"
    EDGE_CASE = "edge_case"
    ACCESSIBILITY = "accessibility"


class TestAction(str, Enum):
    """Controlled vocabulary of actions that the Test Planner may emit.

    Each action maps to an operation that Member 2's execution engine
    can perform.  The Test Planner must NOT generate actions outside
    this vocabulary.

    Action Requirements
    -------------------
    ============  ==============  ==============
    Action        Target Required Value Required
    ============  ==============  ==============
    NAVIGATE      No              Yes (URL)
    CLICK         Yes             No
    FILL          Yes             Yes (text)
    SELECT        Yes             Yes (option)
    CHECK         Yes             No
    UNCHECK       Yes             No
    PRESS         No              Yes (key name)
    WAIT          No              No
    ============  ==============  ==============
    """

    NAVIGATE = "navigate"
    CLICK = "click"
    FILL = "fill"
    SELECT = "select"
    CHECK = "check"
    UNCHECK = "uncheck"
    PRESS = "press"
    WAIT = "wait"


class AssertionType(str, Enum):
    """Controlled vocabulary of assertion types.

    The Test Planner must only produce assertions whose ``type``
    matches one of these values.  Member 2's execution engine maps
    each type to a concrete verification step.
    """

    ELEMENT_VISIBLE = "element_visible"
    ELEMENT_NOT_VISIBLE = "element_not_visible"
    ELEMENT_CONTAINS_TEXT = "element_contains_text"
    ELEMENT_HAS_TEXT = "element_has_text"
    URL_CONTAINS = "url_contains"
    URL_EQUALS = "url_equals"
    VALUE_EQUALS = "value_equals"
