"""
TestSphere-AI — Shared Enumerations

Defines all enums used across the AI intelligence layer and
inter-member communication contracts.
"""

from enum import Enum


class FailureType(str, Enum):
    """Classification categories for test failures.

    Used by the Failure Analysis Agent to categorize why a test failed,
    which determines whether self-healing is applicable.
    """

    ELEMENT_NOT_FOUND = "ELEMENT_NOT_FOUND"
    ELEMENT_NOT_INTERACTABLE = "ELEMENT_NOT_INTERACTABLE"
    TIMEOUT = "TIMEOUT"
    ASSERTION_FAILURE = "ASSERTION_FAILURE"
    NAVIGATION_FAILURE = "NAVIGATION_FAILURE"
    NETWORK_ERROR = "NETWORK_ERROR"
    APPLICATION_ERROR = "APPLICATION_ERROR"
    UNKNOWN = "UNKNOWN"


class HealingStatus(str, Enum):
    """Status of a healing attempt.

    Tracks the lifecycle of a self-healing operation from proposal
    through validation by Member 2's execution engine.
    """

    PROPOSED = "PROPOSED"
    VALIDATION_PENDING = "VALIDATION_PENDING"
    VALIDATED_SUCCESS = "VALIDATED_SUCCESS"
    VALIDATED_FAILURE = "VALIDATED_FAILURE"
    NO_SAFE_HEALING_FOUND = "NO_SAFE_HEALING_FOUND"


class TestPriority(str, Enum):
    """Priority levels for generated test cases."""

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class TestCategory(str, Enum):
    """Categories of test cases generated by the Test Planner."""

    FUNCTIONAL = "functional"
    SMOKE = "smoke"
    REGRESSION = "regression"
    EDGE_CASE = "edge_case"
    ACCESSIBILITY = "accessibility"
