"""
TestSphere-AI — Shared Enumerations

Defines all enums used across the AI intelligence layer and
inter-member communication contracts.
"""

from enum import Enum


class FailureType(str, Enum):
    """Classification categories for test failures.

    Used by the Failure Analysis Agent to categorize why a test failed,
    which determines whether self-healing is applicable.
    """

    SELECTOR_CHANGED = "SELECTOR_CHANGED"
    ELEMENT_NOT_FOUND = "ELEMENT_NOT_FOUND"
    ELEMENT_NOT_INTERACTABLE = "ELEMENT_NOT_INTERACTABLE"
    TIMEOUT = "TIMEOUT"
    ASSERTION_FAILURE = "ASSERTION_FAILURE"
    NAVIGATION_FAILURE = "NAVIGATION_FAILURE"
    NETWORK_ERROR = "NETWORK_ERROR"
    APPLICATION_ERROR = "APPLICATION_ERROR"
    UNKNOWN = "UNKNOWN"


class HealingStatus(str, Enum):
    """Status of a healing attempt.

    Tracks the lifecycle of a self-healing operation from proposal
    through validation by Member 2's execution engine.
    """

    PROPOSED = "PROPOSED"
    VALIDATION_PENDING = "VALIDATION_PENDING"
    VALIDATED_SUCCESS = "VALIDATED_SUCCESS"
    VALIDATED_FAILURE = "VALIDATED_FAILURE"
    NO_SAFE_HEALING_FOUND = "NO_SAFE_HEALING_FOUND"


class TestPriority(str, Enum):
    """Priority levels for generated test cases.

    Definitions
    -----------
    CRITICAL:
        System-critical functionality whose failure blocks all usage.
    HIGH:
        Critical user workflows or high-impact functionality.
        Examples: Login, Signup, Payment, Checkout, critical form submission.
    MEDIUM:
        Important functionality that is not immediately business-critical.
    LOW:
        Minor or low-impact functionality.
    """

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class TestCategory(str, Enum):
    """Categories of test cases generated by the Test Planner.

    Definitions
    -----------
    FUNCTIONAL:
        Tests expected normal user workflows.
    NEGATIVE:
        Tests invalid or incorrect input/workflows.
    BOUNDARY:
        Tests minimum, maximum, empty, or edge-case values.
    SMOKE:
        Quick sanity checks that core features work.
    REGRESSION:
        Tests that verify previously working functionality still works.
    EDGE_CASE:
        Tests for unusual or extreme conditions.
    ACCESSIBILITY:
        Tests that verify accessibility compliance.
    """

    FUNCTIONAL = "functional"
    NEGATIVE = "negative"
    BOUNDARY = "boundary"
    SMOKE = "smoke"
    REGRESSION = "regression"
    EDGE_CASE = "edge_case"
    ACCESSIBILITY = "accessibility"


class TestAction(str, Enum):
    """Controlled vocabulary of actions that the Test Planner may emit.

    Each action maps to an operation that Member 2's execution engine
    can perform.  The Test Planner must NOT generate actions outside
    this vocabulary.

    Action Requirements
    -------------------
    ============  ==============  ==============
    Action        Target Required Value Required
    ============  ==============  ==============
    NAVIGATE      No              Yes (URL)
    CLICK         Yes             No
    FILL          Yes             Yes (text)
    SELECT        Yes             Yes (option)
    CHECK         Yes             No
    UNCHECK       Yes             No
    PRESS         No              Yes (key name)
    WAIT          No              No
    ============  ==============  ==============
    """

    NAVIGATE = "navigate"
    CLICK = "click"
    FILL = "fill"
    SELECT = "select"
    CHECK = "check"
    UNCHECK = "uncheck"
    PRESS = "press"
    WAIT = "wait"


class AssertionType(str, Enum):
    """Controlled vocabulary of assertion types.

    The Test Planner must only produce assertions whose ``type``
    matches one of these values.  Member 2's execution engine maps
    each type to a concrete verification step.
    """

    ELEMENT_VISIBLE = "element_visible"
    ELEMENT_NOT_VISIBLE = "element_not_visible"
    ELEMENT_CONTAINS_TEXT = "element_contains_text"
    ELEMENT_HAS_TEXT = "element_has_text"
    URL_CONTAINS = "url_contains"
    URL_EQUALS = "url_equals"
    VALUE_EQUALS = "value_equals"


class ExecutionStatus(str, Enum):
    """Status of a test execution.

    Used by the Historical Memory layer to track test execution
    outcomes over time.
    """

    PASSED = "PASSED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    ERROR = "ERROR"


class ChangeType(str, Enum):
    """Classification of a field-level change between two element snapshots.

    Used by the Context Comparator to describe how individual
    fields differ between a previous and current element state.
    """

    ADDED = "ADDED"
    REMOVED = "REMOVED"
    MODIFIED = "MODIFIED"
    UNCHANGED = "UNCHANGED"


class ConfidenceLevel(str, Enum):
    """Confidence level for a failure analysis.

    Used by the Failure Analysis Agent to indicate how certain
    the diagnosis is, based on available evidence.

    Definitions
    -----------
    HIGH:
        Strong evidence from history and current context supports
        the classification (e.g. previous selector existed, current
        missing, equivalent element found).
    MEDIUM:
        Partial evidence exists but some ambiguity remains
        (e.g. previous selector existed, current missing,
        similar but not identical element found).
    LOW:
        Insufficient historical or current evidence to make
        a confident classification.
    """

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class RecommendedAction(str, Enum):
    """Recommended next action after failure analysis.

    The Failure Analysis Agent recommends what the future
    Self-Healing Agent or operator should do next.  These are
    recommendations only — the analyzer does NOT execute them.
    """

    SEARCH_FOR_REPLACEMENT_SELECTOR = "SEARCH_FOR_REPLACEMENT_SELECTOR"
    INSPECT_CURRENT_UI = "INSPECT_CURRENT_UI"
    CHECK_ELEMENT_STATE = "CHECK_ELEMENT_STATE"
    ANALYZE_APPLICATION_STATE = "ANALYZE_APPLICATION_STATE"
    INVESTIGATE_TIMEOUT = "INVESTIGATE_TIMEOUT"
    INVESTIGATE_NAVIGATION = "INVESTIGATE_NAVIGATION"
    REQUIRE_FURTHER_ANALYSIS = "REQUIRE_FURTHER_ANALYSIS"


class HealingAction(str, Enum):
    """Controlled vocabulary of healing recommendation actions.

    Used by the Healing Decision Engine (Day 10) to indicate what
    Member 2's Self-Healing Engine should attempt.  These are
    recommendations only — the intelligence layer does NOT execute them.

    Definitions
    -----------
    TRY_REPLACEMENT_SELECTOR:
        A high-confidence replacement selector candidate has been
        identified.  Member 2 should attempt to use it.
    SEARCH_CURRENT_UI:
        No strong candidate was found from available context.
        Member 2 should perform a broader UI search.
    REQUIRE_FURTHER_ANALYSIS:
        Evidence is insufficient or ambiguous.  The failure needs
        additional investigation before healing can be attempted.
    DO_NOT_HEAL:
        Healing is not appropriate for this failure type (e.g.
        assertion failures) or no candidate meets the minimum
        confidence threshold.
    """

    TRY_REPLACEMENT_SELECTOR = "TRY_REPLACEMENT_SELECTOR"
    SEARCH_CURRENT_UI = "SEARCH_CURRENT_UI"
    REQUIRE_FURTHER_ANALYSIS = "REQUIRE_FURTHER_ANALYSIS"
    DO_NOT_HEAL = "DO_NOT_HEAL"


class HealingDecision(str, Enum):
    """Final healing decision from the intelligence layer.

    Captures the overall assessment of whether healing should
    proceed, independent of the specific action recommended.

    Definitions
    -----------
    RECOMMEND_HEALING:
        High-confidence candidate found.  Recommend sending to
        Member 2 for browser validation.
    REQUIRE_VALIDATION:
        Medium-confidence candidate found.  Recommend candidate
        but require additional validation by Member 2.
    REQUIRE_FURTHER_ANALYSIS:
        Candidates are ambiguous or insufficient.  Further
        investigation is needed before healing can proceed.
    DO_NOT_HEAL:
        Healing is not appropriate (e.g. assertion failure,
        no candidates, confidence below minimum threshold).
    """

    RECOMMEND_HEALING = "RECOMMEND_HEALING"
    REQUIRE_VALIDATION = "REQUIRE_VALIDATION"
    REQUIRE_FURTHER_ANALYSIS = "REQUIRE_FURTHER_ANALYSIS"
    DO_NOT_HEAL = "DO_NOT_HEAL"


class CandidateSource(str, Enum):
    """Source of a healing candidate selector.

    Tracks where a candidate replacement selector originated from,
    providing transparency for debugging and confidence calibration.

    Definitions
    -----------
    HISTORICAL_MEMORY:
        Candidate was found by comparing against historical element
        records stored in the memory layer.
    CURRENT_DOM:
        Candidate was identified from current UI elements provided
        in the failure context.
    LLM_SUGGESTION:
        Candidate was suggested by the LLM during disambiguation
        of ambiguous or tied candidates.
    """

    HISTORICAL_MEMORY = "HISTORICAL_MEMORY"
    CURRENT_DOM = "CURRENT_DOM"
    LLM_SUGGESTION = "LLM_SUGGESTION"
